server:
  port: 8090

spring:
  redis:
    password: sOmE_sEcUrE_pAsS
  codec:
    max-in-memory-size: 10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

f2:
  tenant:
    issuer-base-uri: http://keycloak-it:8080

fs:
  space:
#   name: fs-sample
    jwt:
      claims: space
  s3:
    internal-url: http://localhost:9000
    external-url: http://localhost:9000
    region: us-west-1
    username: minio
    password: minio123
    bucket: fs-sample
    dns: false
  ssm:
    channel: sandbox
    chaincode: ssm
    signerName: ${ssm.signer.admin.name}
    signerFile: ${ssm.signer.admin.key}
  kb:
    url: http://localhost:9999

i2:
  issuers:
ssm:
  signer:
    user:
      name: ssm-admin
      key: user/ssm-admin
    admin:
      name: ssm-admin
      key: user/ssm-admin

---
spring:
  config:
    activate:
      on-profile: local

f2:
  tenant:
    issuer-base-uri: http://localhost:8080

fs:
  s3:
    username: minio
  ssm:
    directories:
      - important
  init:
    buckets: fs-sample, fs-sample-test

#ssm:
#  couchdb:
#    url: http://localhost:5984
#    username: couchdb
#    password: couchdb
#    serviceName: fs-sample
#  chaincode:
#    url: http://localhost:9090
