server:
  port: 8090

spring:
  redis:
    password: sOmE_sEcUrE_pAsS

fs:
  s3:
    url: http://localhost:9000
    region: us-west-1
    username: minio
    password: minio123
    bucket: fs-sample
    dns: false
  ssm:
    channel: sandbox
    chaincode: ssm
    signerName: ${ssm.signer.admin.name}
    signerFile: ${ssm.signer.admin.key}
    categories:
      - important

ssm:
  signer:
    user:
      name: ssm-admin
      key: user/ssm-admin
    admin:
      name: ssm-admin
      key: user/ssm-admin
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: fs-sample
  chaincode:
    url: http://localhost:9090
