include:
  - project: 'framework/fixers/cicd'
    file: 'make/.gitlab-ci.yml'

stages:
  - package

api:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package

docs:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: docs
