include:
  - project: 'fixers/cicd'
    file: 'make/.gitlab-ci.yml'

stages:
  - package

##########################################
## Tasks
##########################################

api:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-gateway

web:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-web

docs:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package-docs
