include:
  - project: 'fixers/cicd'
    file: 'make/.gitlab-ci.yml'

stages:
  - package
  - docs

api:
  stage: package
  extends:
    - .make
  variables:
    MAKE_TARGET: package

docs:
  stage: docs
  extends:
    - .make
  variables:
    MAKE_TARGET: docs
