services:
  fs-migrate:
    image: fs-script:0.22.0-SNAPSHOT
    container_name: fs-migrate
    environment:
      - FS_SCRIPT_MIGRATE_ENABLED=true
      - FS_SCRIPT_MIGRATE_DRY_RUN=${FS_SCRIPT_MIGRATE_DRY_RUN}
      - FS_SCRIPT_MIGRATE_BUCKETS=${FS_SCRIPT_MIGRATE_BUCKETS}
      - FS_SCRIPT_MIGRATE_CONCURRENCY=${FS_SCRIPT_MIGRATE_CONCURRENCY}
      - FS_SCRIPT_MIGRATE_DELETE_EXTRANEOUS=${FS_SCRIPT_MIGRATE_DELETE_EXTRANEOUS}
      - FS_SCRIPT_RETRY_MAX=${FS_SCRIPT_RETRY_MAX}
      - FS_SCRIPT_RETRY_DELAY_MILLIS=${FS_SCRIPT_RETRY_DELAY_MILLIS}
      # Source: the MinIO server being migrated from
      - FS_MIGRATE_SOURCE_URL=${FS_S3_INTERNAL_URL}
      - FS_MIGRATE_SOURCE_USERNAME=${FS_S3_USERNAME}
      - FS_MIGRATE_SOURCE_PASSWORD=${FS_S3_PASSWORD}
      # Target: the RustFS server being migrated to
      - FS_S3_INTERNAL_URL=${FS_RUSTFS_INTERNAL_URL}
      - FS_S3_EXTERNAL_URL=${FS_RUSTFS_INTERNAL_URL}
      - FS_S3_USERNAME=${FS_RUSTFS_ACCESS_KEY}
      - FS_S3_PASSWORD=${FS_RUSTFS_SECRET_KEY}
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
